import type { ProductData } from './types';

export const PRODUCT_DATA: ProductData[] = [
  {
    id: 1,
    image: 'https://picsum.photos/400/400?random=1',
    title: 'Cardholder + Photocard',
    price: 17800,
    originalPrice: 30000,
    discount: 41,
    tags: ['무료배송', '특가'],
    brand: 'Brand A',
  },
  {
    id: 2,
    image: 'https://picsum.photos/400/400?random=2',
    title: 'Random Trading Card',
    price: 11900,
    originalPrice: 32000,
    discount: 63,
    tags: ['단독구성'],
    brand: 'Brand B',
  },
  {
    id: 3,
    image: 'https://picsum.photos/400/400?random=3',
    title: 'Acrylic Keyring',
    price: 20900,
    originalPrice: 3300,
    discount: 63,
    tags: ['단독구성'],
    brand: 'Brand C',
  },
  {
    id: 4,
    image: 'https://picsum.photos/400/400?random=4',
    title: 'Fabric Poster',
    price: 20900,
    originalPrice: 3300,
    discount: 63,
    tags: ['단독구성'],
    brand: 'Brand D',
  },
  {
    id: 5,
    image: 'https://picsum.photos/400/400?random=5',
    title: 'Mini Photo Album',
    price: 15000,
    originalPrice: 25000,
    discount: 40,
    tags: ['인기'],
    brand: 'Brand E',
  },
  {
    id: 6,
    image: 'https://picsum.photos/400/400?random=6',
    title: 'Sticker Set',
    price: 8900,
    originalPrice: 15000,
    discount: 41,
    tags: ['무료배송'],
    brand: 'Brand F',
  },
];
